name: MedPatient
options:
  bundleIdPrefix: com.medmanager
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: "Automatic"
targets:
  MedPatient:
    type: application
    platform: iOS
    sources:
      - MedPatient
      - Features
      - Services
      - Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.medmanager.patient
        INFOPLIST_FILE: MedPatient/Info.plist
    scheme:
      testTargets:
        - MedPatientTests
  MedPatientTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - MedPatientTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.medmanager.patientTests
        INFOPLIST_FILE: MedPatientTests/Info.plist
    dependencies:
      - target: MedPatient
